"""empty message

Revision ID: 9af19e00d051
Revises: 
Create Date: 2018-07-31 10:57:10.013501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9af19e00d051'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cameras',
    sa.Column('cameraid', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('last_width', sa.Integer(), nullable=True),
    sa.Column('last_height', sa.Integer(), nullable=True),
    sa.Column('mhash', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('cameraid')
    )
    op.create_table('submit_cams',
    sa.Column('submitid', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('curr_time', sa.DateTime(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('submitid')
    )
    op.create_table('images',
    sa.Column('rowid', sa.Integer(), nullable=False),
    sa.Column('filepath', sa.String(), nullable=True),
    sa.Column('curr_time', sa.DateTime(), nullable=True),
    sa.Column('cameraid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cameraid'], ['cameras.cameraid'], ),
    sa.PrimaryKeyConstraint('rowid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('images')
    op.drop_table('submit_cams')
    op.drop_table('cameras')
    # ### end Alembic commands ###
